### ISSUE TITLE
Combining result document can not be often with error message.

### ISSUE THREAD

**Issue by jinguohao1991** [4teamwork/docxcompose#49] opened 2020-02-21 09:16 UTC
Hi.
Thank you for providing greate framework!
But I have got issue using this frame work.
![image](https://user-images.githubusercontent.com/31640360/75020501-d5c97500-54cd-11ea-92e0-3c459e315bf6.png)
Hope your help.

**Comment by njohner** [comment] 2022-07-04 15:56
I'll close this because it's old and because of lack of information. Minimal set of docx files to reproduce the issue is the minimum that should be provided.

**Closed by njohner** 2022-07-04 15:56 UTC
